template: Hello, %s!
defaultName: Stranger

# Database settings.
database:
  # the name of the JDBC driver, mysql in our case
  driverClass: com.mysql.jdbc.Driver
  # the username
  user: root
  # the password
  password: ''
  # the JDBC URL; the database is called teeny
  url: jdbc:mysql://localhost:3306/teeny